# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
env:
  - PROJECT_DESCRIPTION=Watch-up is a simple url monitoring tool that checks if a website is up or down.
  - PROJECT_HOMEPAGE=https://github.com/nousefreak/watch-up
  - LICENSE=MIT

version: 1

builds:
  - main: ./cmd/watch-up
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: 'checksums.txt'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

brews:
  - repository:
      owner: nousefreak
      name: homebrew-brew
    folder: Formula
    homepage: "{{ .Env.PROJECT_HOMEPAGE }}"
    description: "{{ .Env.PROJECT_DESCRIPTION }}"
    license: "{{ .Env.LICENSE }}"
    test: |
      system "#{bin}/{{ .ProjectName }} help"
    dependencies: []
    install: |-
      bin.install "{{ .ProjectName }}"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/nousefreak/watch-up
    description: "{{ .Env.PROJECT_DESCRIPTION}}"
    maintainer: Dries De Peuter <dries@stenic.io>
    license: MIT
    vendor: NoUseFreak
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/watch-up/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
